---
management:
  security:
    enabled: false
  context-path: /
  port: 8081
---
spring:
  h2:
    console:
      enabled: true
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/bootex
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/bootex
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:bootex;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    com.lezhin: TRACE
endpoints:
  enabled: false
